=== khameds/doc_numerique/chat.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT chat (message*)>
<!ATTLIST chat
	evenementId CDATA #REQUIRED
>
<!ELEMENT message (date,auteur,auteurId,texte)>
<!ATTLIST message
	idUtilisateur CDATA #REQUIRED
	idEvenement CDATA #REQUIRED
>
<!ELEMENT date (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT auteurId (#PCDATA)>
<!ELEMENT texte (#PCDATA)>

=== khameds/doc_numerique/chat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chat SYSTEM "chat.dtd">
<chat evenementId="1">
    <message idUtilisateur="1" idEvenement="1">
    <date>2017</date>
    <auteur>1</auteur>
    <auteurId>1</auteurId>
    <texte>Salut</texte>
    </message>
    <message idUtilisateur="2" idEvenement="1">
    <date>2018</date>
    <auteur>2</auteur>
    <auteurId>2</auteurId>
    <texte>Salut</texte>
    </message>
</chat>
