=== khameds/doc_numerique/fichiers_definitions/definition.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="fichier">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="header" type="xs:complexType">
                    <xs:attribute name="fileId" type="xs:ID" use="required"/>
                    <xs:sequence>
                        <xs:element name="nbMessages" type="xs:positiveInteger"/>
                        <xs:element name="institution" type="xs:string"/>
                    </xs:sequence>
                </xs:element>

                <xs:element name="collMess" type="xs:complexType">
                    <xs:sequence>
                        <xs:element name="message" minOccurs="0" maxOccurs="unbounded" type="xs:complexType">
                            <xs:attribute name="messageId" type="xs:ID" use="required"/>
                            <xs:sequence>
                                <xs:element name="mailDest" minOccurs="0" maxOccurs="unbounded" type="email"/>
                                <xs:element name="mailExp" minOccurs="0" type="email"/>
                                <xs:choice>
                                    <xs:element name="information" type="information"
                                </xs:choice>
                            </xs:sequence>
                        </xs:element>
                    </xs:sequence>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="^[a-zA-Z][\w\.-]*[a-zA-Z0-9]@[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]$"/>
        </xs:restriction>
    </xs:simpleType>


    <!ELEMENT message (mailDest*, mailExp?,(information|autorisation|demande|reponse))>
    <!ATTLIST messageId ID #REQUIRED>

    <!ELEMENT mailDest (#PCDATA)>
    <!ELEMENT mailExp (#PCDATA)>
    <!ELEMENT information (sujet,dateDebut,duree,contenuTexte)>
    <!ELEMENT contenuTexte (#PCDATA)>
    <!ELEMENT duree (#PCDATA)>
    <!ELEMENT sujet (#PCDATA)>
    <!ELEMENT dateDebut (#PCDATA)>
    <!ELEMENT autorisation (autorisationID, dateDebut, duree)>
    <!ELEMENT autorisationID (#PCDATA)>
    <!ELEMENT demande (sujet,dateDebut,duree)>
    <!ATTLIST authId ID (#REQUIRED) >
    <!ATTLIST dateSign (#REQUIRED #PCDATA)>
    <!ELEMENT reponse (sujet, contenuTexte) >
    <!ATTLIST messageId IDREF (#REQUIRED)>
    <!ATTLIST reponseId ID (#REQUIRED)>


    <xs:complexType name="information">
        <xs:sequence>
            <xs:element name="sujet">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="dateDebut" type="xs:date"/>
            <xs:element name="duree" type="duree"/>

        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="duree">
        <xs:choice>
            <xs:element name="semaines" type="xs:positiveInteger"/>
            <xs:element name="mois" type="xs:positiveInteger"/>
        </xs:choice>
    </xs:complexType>

=== khameds/doc_numerique/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<fichier xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="fichiers_definition/definition.xsd">
    <header fileID=1>
        <nbMessages>1</nbMessages>
        <institution>L'institution du cul</institution>
    </header>
    <collMess>
        <message messageId=1>
            <mailDest>jacquie@michel.fr</mailDest>
            <mailExp>marc@dorcel.fr</mailExp>
        </message>
        <information>
            <sujet>Michel</sujet>
            <contenuTexte>Salut, j'aimerais avoir michel pour un tournage</contenuTexte>
            <dateDebut>1/1/2018</dateDebut>
            <duree>
                <semaines>1</semaines>
            </duree>
        </information>
    </collMess>
</fichier>

=== khameds/doc_numerique/fichiers_test/non_valides/no_header.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Fichier de Test :
  Cible : Validation de la structure du fichier
  Résultat attendu : Fichier rejeté car le noeud "header" est absent
-->

<fichier xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../fichiers_definitions/definition.xsd">
    <collMess>
        <message messageId="m1">
            <emailExp>marc@dorcel.fr</emailExp>
            <information>
                <sujet>Michel</sujet>
                <contenuTexte>Salut, j'aimerais avoir michel pour un tournage</contenuTexte>
                <dateDebut>2018-01-01</dateDebut>
                <duree>
                    <semaines>1</semaines>
                </duree>
            </information>
        </message>
    </collMess>
</fichier>

=== khameds/doc_numerique/fichiers_test/non_valides/syntaxe/not_well_formed_1.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Fichier de Test :
  Cible : Validation de la structure du fichier
  Résultat attendu : Fichier rejeté car le fichier n'est pas "bien formé".
  La balise "CollMess" n'est pas fermée.
-->

<fichier xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../fichiers_definitions/definition.xsd">

    <header fileId="f1">
        <nbMessages>1</nbMessages>
        <institution>L'institution</institution>
    </header>
    <collMess>
        <message messageId="m1">
            <emailExp>jacquie@michel.fr</emailExp>
            <information>
                <sujet>Michel</sujet>
                <contenuTexte>Salut, j'aimerais avoir michel pour un tournage</contenuTexte>
                <dateDebut>2018-01-01</dateDebut>
                <duree>
                    <semaines>1</semaines>
                </duree>
            </information>
        </message>
</fichier>

=== khameds/doc_numerique/fichiers_test/valides/some_informations.xml
<?xml version="1.0" encoding="UTF-8" ?>
<fichier xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../fichiers_definitions/definition.xsd">

    <header fileId="12">
        <nbMessages>4</nbMessages>
        <institution>L'institution</institution>
    </header>
    <collMess>
        <message messageId="1">
        <emailExp>jacquie@michel.fr</emailExp>
        <emailExp>marc@dorcel.fr</emailExp>
        <information>
            <sujet>Michel</sujet>
            <contenuTexte>Salut, j'aimerais avoir michel pour un tournage</contenuTexte>
            <dateDebut>1/1/2018</dateDebut>
            <duree>
                <semaines>1</semaines>
            </duree>
        </information>
    </message>
        <message messageId="2">
            <information>
                <sujet>Michel</sujet>
                <contenuTexte>Salut, il participera au tournage!</contenuTexte>
                <dateDebut>1/1/2018</dateDebut>
                <duree>
                    <semaines>1</semaines>
                </duree>
            </information>
        </message>
        <message messageId="3">
            <information>
                <sujet>Toujours Michel</sujet>
                <contenuTexte>Il a chopé un truc, il est sous antibiotique, c pas génant?</contenuTexte>
                <dateDebut>1/1/2018</dateDebut>
                <duree>
                    <semaines>1</semaines>
                </duree>
            </information>
        </message>
        <message messageId="4">
            <information>
                <sujet>toujours plus de Michel</sujet>
                <contenuTexte>Ouep osef, l'autre est toute bouffée de l'interieur aussi...</contenuTexte>
                <dateDebut>1/1/2018</dateDebut>
                <duree>
                    <semaines>1</semaines>
                </duree>
            </information>
        </message>
    </collMess>
</fichier>
